<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Price_Final</name>
   <tag></tag>
   <elementGuidId>032308db-44ac-4595-a3fb-4dca1c1adb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;product-info-main&quot;]//*[contains(@id,&quot;product-price&quot;)]//*[@class=&quot;price&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37703670-7245-4f3f-882b-c99171454be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>bb1d19a9-fb72-4621-af1c-42dd4521217e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>49,90 €</value>
      <webElementGuid>ee6926a0-77ee-4bd2-9aa7-5409dd30866c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-price-3869&quot;)/span[@class=&quot;price&quot;]</value>
      <webElementGuid>85430744-c3da-43d6-a973-89e53b37ce4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[contains(@id,'product-price')]/span</value>
      <webElementGuid>bd6faef0-6212-4600-88f8-3e6f6ed395d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ab'])[1]/following::span[2]</value>
      <webElementGuid>df18414a-08df-4d38-8d7b-a65c96cd69d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inkl. MwSt.'])[1]/preceding::span[2]</value>
      <webElementGuid>dc5ee4f2-4fb9-4403-9ccb-e468f8591604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farbe'])[1]/preceding::span[2]</value>
      <webElementGuid>0492f349-18b5-4470-abfc-20989e63b888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='49,90 €']/parent::*</value>
      <webElementGuid>56e3deb6-c598-4f7c-87d1-141c6af54545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/span</value>
      <webElementGuid>071218c0-a063-4c7c-af03-0d0fbf47d06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//*[@data-price-type=&quot;finalPrice&quot;]</value>
      <webElementGuid>ddf3fd87-e568-48c1-af39-cb5b13ffc338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
