<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jetzt lesen</name>
   <tag></tag>
   <elementGuidId>d9afd910-484b-40b0-bfe3-9e89a3b3b18c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.button.page.page-next.gtmTriggerClick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/section/div/div/section/div/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b0efbf1-e766-4bd5-9994-7ba5fd7c40d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button page page-next gtmTriggerClick</value>
      <webElementGuid>0378e855-004e-429d-b192-b932b3298247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-category</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>31b68e7b-5ae3-4724-beab-5b22c4b1f2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-action</name>
      <type>Main</type>
      <value>home-cat-main</value>
      <webElementGuid>7c379a09-e248-467a-87d2-8cb0f1058b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-label</name>
      <type>Main</type>
      <value>page page-next</value>
      <webElementGuid>195b5eb1-37c5-492f-8b2c-bd211ad48e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>9ab647b7-d5b0-4322-b29e-41f45181fa2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>11a9490f-6ae7-4d5b-a0c0-ff5c5c63cab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f7aae030-0798-4d26-96f6-26e342e46d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;row borderless&quot;]/div[@class=&quot;col-12&quot;]/section[@class=&quot;slider banner slider-no-divider slider-catalog-category qbertSlider initialized&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12&quot;]/div[@class=&quot;inner&quot;]/span[@class=&quot;button page page-next gtmTriggerClick&quot;]</value>
      <webElementGuid>4b95199a-0245-4e53-a1a2-fb9cd3fde302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/section/div/div/section/div/div/div/span[2]</value>
      <webElementGuid>53e3690e-ab0a-4476-8964-2689af92ffc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
      <webElementGuid>17cc685f-83f4-492a-8f92-479b2aef0c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
