<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_In den Warenkorb</name>
   <tag></tag>
   <elementGuidId>2c0247e1-6d61-460a-947c-460067eaef14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-addtocart-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='product-addtocart-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>276f7857-47da-4b16-9706-dc8825bb51f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>862a9493-d335-4aeb-993c-39425c8af643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>In den Warenkorb</value>
      <webElementGuid>00d33119-e47c-4c46-807f-9bfe6ee944f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action primary tocart gtmTriggerClick</value>
      <webElementGuid>c3c02b3e-fba3-433f-9925-9d9b166e8467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-category</name>
      <type>Main</type>
      <value>catalog</value>
      <webElementGuid>e44665f0-abab-4411-baef-404b3f16ece7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-action</name>
      <type>Main</type>
      <value>addToCart</value>
      <webElementGuid>cb7812c4-8b7f-4929-81ed-c5154f22a117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-label</name>
      <type>Main</type>
      <value>10020810</value>
      <webElementGuid>1a9878d5-3113-40d8-b629-34fbd089ee0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-addtocart-button</value>
      <webElementGuid>5be9c3a0-e781-4170-8cd3-6b09353840a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In den Warenkorb</value>
      <webElementGuid>7015a996-200c-4460-b766-5da85b6b3bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-addtocart-button&quot;)</value>
      <webElementGuid>cf0c006a-68ab-41db-8f40-5ebaa0049c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='product-addtocart-button']</value>
      <webElementGuid>bc06d6e8-2b3d-47c6-bf1e-7f15b59d7127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>46d38f88-a6d4-4514-82f7-14cdeb4998d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dunkelblau | Weiß | Transparent'])[1]/following::button[1]</value>
      <webElementGuid>65dd1bf2-7db6-404d-8baf-7cf58174d109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farbe'])[1]/following::button[1]</value>
      <webElementGuid>9e0c1a57-5496-43e5-9fce-731fb03a240a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zur Wunschliste hinzufügen'])[1]/preceding::button[1]</value>
      <webElementGuid>2642b700-68a1-44e5-884d-94b69c1d596e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>25e4bc74-dd11-4ee4-84d0-8ce204849c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'In den Warenkorb' and @id = 'product-addtocart-button' and (text() = 'In den Warenkorb' or . = 'In den Warenkorb')]</value>
      <webElementGuid>ff6c7a71-cdad-4780-8306-af0ef2c654a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
