<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_color_attribute_basket</name>
   <tag></tag>
   <elementGuidId>a9c4cd08-6952-4f1e-8979-6df960b6e0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@class,'item-options')]//*[text()='Farbe']/following-sibling::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dd</value>
      <webElementGuid>0916ca48-5432-4a34-be54-feefd92b2c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dunkelblau | Weiß | Transparent </value>
      <webElementGuid>c14a74a0-e4be-40bd-9e66-9f0952be552b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-table&quot;)/div[@class=&quot;divider margin-bottom-s padding-bottom-s&quot;]/div[@class=&quot;row row-padding-xs cart-item&quot;]/div[@class=&quot;col-8 col-sm-9 col-lg-10&quot;]/div[@class=&quot;row row-padding-xs margin-bottom-s min-height-65&quot;]/div[@class=&quot;col-10 col-md-10&quot;]/div[2]/dl[@class=&quot;item-options&quot;]/dd[1]</value>
      <webElementGuid>2688ae11-2897-4efe-9f38-4c0d78f10202</webElementGuid>
   </webElementProperties>
</WebElementEntity>
